### ISSUE TITLE
can't get user added to group

### ISSUE THREAD

**Issue by seapasulli** [camptocamp/puppet-accounts#23]
I am new to puppet and foreman so I am probably doing something wrong::

I can not seem to get the accounts to add my admin user to the staff group. I am not sure if I am doing something wrong but the documentation is confusing. It looks like anything specified in the usergroups should make it in but then user::accounts shows anything specified in groups is added to user. 

I currently have usergroups populated with a hash as follows::
```yaml
admin:
- admin
- staff
- sudo
- wheel
```
groups hash as follows:::
```yaml
staff:
  ensure: present
sudo:
  ensure: present
wheel:
  ensure: present
```
My users hash:
```yaml
admin:
  comment: administrator user
  password: $6$...
  shell: /bin/bash
```
Finally:: My Accounts hash::
```yaml
admin:
  authorized_keys:
  - user1
  - user2
  - admin
```

Would you mind clarifying this a bit?

**Comment by johnzimm** [comment]
This was a bit confusing to me at first too.  My understanding is the group hash is basically groups of user accounts you'd like to provision and not actual groups on the Linux system.  As in "I'd like to provision all users in my admin hash on this server".

To add a user to a specific system group on the server you need to add the groups to the accounts.

e.g.

```
users:
  mytestuser:
    comment: "My Test User"
    groups:
      - 'staff'
      - 'wheel'
      - 'backup'
```
