### ISSUE TITLE
'root' management?

### ISSUE THREAD

**Issue by mimmus** [camptocamp/puppet-accounts#44]
Is it possible to manage 'root' account?
- It is obviously always present
- Its homedir is different
- I'd like to add a key under authorized_keys

**Comment by raphink** [comment]
Yes, we do manage `root` with this module.

**Comment by mimmus** [comment]
May you provide me a hiera config to add a key for the 'root' user?

Thanks in advance

**Comment by vdmkenny** [comment]
Do we need to define "root" under `accounts:users?`

When I try to add authorized keys to my root users like this:
```
---
accounts::ssh_keys:
  kenny:
    type: ssh-rsa
    public: 'somekey'
  ben:
    type: ssh-rsa
    public: 'someotherkey'

accounts::users:
  root:
    uid: 0
```

I get 
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, has_key(): expects the first argument to be a hash, got "" which is of type String at /etc/puppetlabs/code/modules/accounts/manifests/account.pp:46:8 
```
