### ISSUE TITLE
Invalid parameter purge_ssh_keys

### ISSUE THREAD

**Issue by hasc** [camptocamp/puppet-accounts#6]
Hi,

I have an issue using this module with puppet 2.7.23 and foreman 1.7.2.

With the following configuration applied:

```yaml
classes:
  accounts:
    accounts:
      exampleuser: {}
    users:
      exampleuser:
        uid: 1001
        comment: Example User
```

I am getting the error:

```log
Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter purge_ssh_keys on node node.example.com
```

Might be I am oding something wrong, however if I comment out line 44 in manifests/accounts.pp everything works.

Thanks in advance
Hannes
